# -*- coding: utf-8 -*-
"""Block module for Decoder-Only Transformer.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oh1fwLcp-tj2OWWxAPnIQcqre8_NwFvu
"""

from torch import nn
from .casual_self_attention import CasualSelfAttention
from .mlp import MLP

class Block(nn.Module):

  def __init__(self, embedding_dim: int, num_head: int, max_seq_length: int, bias: bool=False, dropout: float=0.2):
    super().__init__()

    self.ln_1 = nn.LayerNorm(embedding_dim)
    self.attn = CasualSelfAttention(embedding_dim, num_head, max_token_length=max_seq_length, bias=bias, dropout=dropout)
    self.ln_2 = nn.LayerNorm(embedding_dim)
    self.mlp = MLP(embedding_dim, bias, dropout)

  def forward(self, x):
    x = x + self.attn(self.ln_1(x))
    x = x + self.mlp(self.ln_2(x))

    return x