# -*- coding: utf-8 -*-
"""Generation utilities for Decoder-Only Transformer.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oh1fwLcp-tj2OWWxAPnIQcqre8_NwFvu
"""

import torch.nn.functional as F
from .gpt import GPT

def generate_next_token(model, idx, max_new_tokens, max_seq_length, temperature=1.0, top_k=None):
    """
    Generates new tokens using the provided model.

    Args:
        model: The GPT model instance.
        idx: A torch.Tensor of shape (batch_size, current_sequence_length) representing the input token IDs.
        max_new_tokens: The maximum number of new tokens to generate.
        max_seq_length: The maximum sequence length the model can handle.
        temperature: Controls randomness in sampling. Higher values make output more random.
        top_k: If not None, samples from the top K most likely tokens.

    Returns:
        A torch.Tensor containing the original and newly generated token IDs.
    """
    for _ in range(max_new_tokens):
        # Crop idx to the last max_seq_length tokens if it exceeds the model's capacity
        idx_cond = idx if idx.size(1) <= max_seq_length else idx[:, -max_seq_length:]

        # Get predictions (logits) for the next token
        logits, _ = model(idx_cond)

        # Focus on the logits for the last token in the sequence
        logits = logits[:, -1, :]

        # Apply temperature for sampling
        if temperature != 1.0:
            logits = logits / temperature

        # Apply top-k sampling
        if top_k is not None:
            # Get the top k values and their indices
            v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
            # Set logits of tokens outside the top-k to -infinity
            logits[logits < v[:, [-1]]] = -float('Inf')

        # Convert logits to probabilities using softmax
        probs = F.softmax(logits, dim=-1)

        # Sample the next token from the probability distribution
        idx_next = torch.multinomial(probs, num_samples=1)

        # Append the sampled token to the sequence
        idx = torch.cat((idx, idx_next), dim=1)

    return idx