# -*- coding: utf-8 -*-
"""GPT module for Decoder-Only Transformer.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oh1fwLcp-tj2OWWxAPnIQcqre8_NwFvu
"""

import torch
from torch import nn
import torch.nn.functional as F
from .block import Block

class GPT(nn.Module):

  def __init__(self, embedding_dim: int, num_head: int, max_seq_length: int, vocabulary: int, layers: int, bias: bool=False, dropout: float=0.2):
    super().__init__()
    self.max_seq_length = max_seq_length
    self.transformer = nn.ModuleDict(dict(
        wte = nn.Embedding(vocabulary, embedding_dim),
        wpe = nn.Embedding(max_seq_length, embedding_dim),
        drop = nn.Dropout(dropout),
        # Pass max_seq_length and other parameters correctly to Block
        blocks = nn.ModuleList([Block(embedding_dim, num_head, max_seq_length, bias=bias, dropout=dropout) for _ in range(layers)]),
        ln_f = nn.LayerNorm(embedding_dim),
        head = nn.Linear(embedding_dim, vocabulary, bias=False)
    ))

  def forward(self, idx, targets=None):
    device = idx.device
    b, t = idx.size()

    # Crop idx to max_seq_length if it exceeds the model's capacity
    if t > self.max_seq_length:
        idx = idx[:, -self.max_seq_length:]
        t = self.max_seq_length
        if targets is not None:
            targets = targets[:, -self.max_seq_length:]

    pos = torch.arange(0, t, dtype=torch.long, device=device).unsqueeze(0)

    x = self.transformer.wte(idx) + self.transformer.wpe(pos)
    x = self.transformer.drop(x)

    for block in self.transformer.blocks:
      x = block(x)
    x = self.transformer.ln_f(x)

    logits = None
    loss = None

    if targets is not None:
      logits = self.transformer.head(x)
      loss = F.cross_entropy(
          logits.view(-1, logits.size(-1)),
          targets.view(-1),
          ignore_index = -1,
      )
    else:
        logits = self.transformer.head(x[:,[-1],:])
        loss = None

    return logits, loss