# -*- coding: utf-8 -*-
"""MLP module for Decoder-Only Transformer.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oh1fwLcp-tj2OWWxAPnIQcqre8_NwFvu
"""

from torch import nn

class MLP(nn.Module):

  def __init__(self, embedding_dim: int, bias: bool=False, droput: float=0.2):
    super().__init__()

    self.c_fc = nn.Linear(embedding_dim, 4*embedding_dim, bias=bias)
    self.gelu = nn.GELU()
    self.c_proj = nn.Linear(4*embedding_dim, embedding_dim, bias=bias)
    self.dropout = nn.Dropout(droput)

  def forward(self, x):
    x = self.c_fc(x)
    x = self.gelu(x)
    x = self.c_proj(x)
    x = self.dropout(x)
    return x